name: CI

on:
  workflow_dispatch: {}
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
      - development

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  precheck:
    uses: bennydreamtech23/precheck-developer/.github/workflows/precheck.yml@master
    with:
      project_type: "elixir"
      elixir_version: "1.20.3"
      otp_version: "28.3.1"

  ci:
    uses: bennydreamtech23/precheck-developer/.github/workflows/elixir-ci.yml@master
    with:
      elixir_version: "1.20.3"
      otp_version: "28.3.1"
      postgres_version: "16"
